version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - goloroden
  - yeldiRium
  labels:
  - Dependencies
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.30
    - 14.14.34
    - 15.0.1
  - dependency-name: roboter
    versions:
    - 11.6.10
    - 11.6.17
    - 11.6.22
    - 11.6.26
    - 11.6.28
    - 11.6.29
    - 11.6.31
    - 11.6.33
    - 11.6.36
    - 11.6.39
    - 11.6.7
    - 11.6.8
    - 11.6.9
  - dependency-name: flaschenpost
    versions:
    - 4.3.35
    - 4.3.36
    - 5.0.1
    - 5.0.18
    - 5.0.21
  - dependency-name: semantic-release-configuration
    versions:
    - 2.0.0
  - dependency-name: knockat
    versions:
    - 4.0.50
    - 4.0.53
    - 4.0.58
  commit-message:
    prefix: fix
    prefix-development: chore
